// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./../src/components/Counter.vue')['default']
    CreateProjectDialog: typeof import('./../src/components/CreateProjectDialog.vue')['default']
    DButton: typeof import('./../src/components/DButton.vue')['default']
    DInput: typeof import('./../src/components/DInput.vue')['default']
    DToast: typeof import('./../src/components/DToast/index.vue')['default']
    ProjectBoard: typeof import('./../src/components/ProjectBoard.vue')['default']
    ProjectCard: typeof import('./../src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
