// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreateIcon: typeof import('./../src/components/special/CreateIcon.vue')['default']
    CreateProject: typeof import('./../src/components/bussiness/CreateProject.vue')['default']
    DButton: typeof import('./../src/components/common/DButton.vue')['default']
    DDialog: typeof import('./../src/components/common/DDialog.vue')['default']
    DInput: typeof import('./../src/components/common/DInput.vue')['default']
    ProjectCard: typeof import('./../src/components/bussiness/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrashIcon: typeof import('./../src/components/special/TrashIcon.vue')['default']
  }
}
